#ifndef FREQUENCY_H
#define FREQUENCY_H

#define FREQ_CAPTURE_TIM					TIM2
#define FREQ_CAPTURE_GPIO_AF 				GPIO_AF_TIM2
#define RCC_FREQ_CAPTURE_TIM 				RCC_APB1Periph_TIM2
#define	RCC_FREQ_CAPTURE_GPIO_PORT			RCC_AHB1Periph_GPIOA
#define FREQ_CAPTURE_GPIO_PORT				GPIOA
#define FREQ_CAPTURE_TIM_IRQn				TIM2_IRQn
#define FREQ_CAPTURE_GPIO_PINS				GPIO_Pin_1 | GPIO_Pin_2
#define FREQ_CAPTURE_GPIO_PINSOURCE_1		GPIO_PinSource1
#define FREQ_CAPTURE_GPIO_PINSOURCE_2		GPIO_PinSource2
#define FREQ_CAPTURE_TIM_IRQHandler 		TIM2_IRQHandler
#define FREQ_CAPTURE_TIM_PERIOD				(0xFFFFFFFF)
#define FREQ_CAPTURE_TIMER_TICK_FREQUENCY	19999592//20000000///12000000
#define FREQ_CAPTURE_PERIOD_0_HZ			10000
#define FREQ_CAPTURE_IC_FILTER				5
#define FREQ_CAPTURE_CHN_1					TIM_Channel_2
#define FREQ_CAPTURE_CHN_2					TIM_Channel_3
#define FREQ_CAPTURE_IT_1					TIM_IT_CC2
#define FREQ_CAPTURE_IT_2					TIM_IT_CC3
#define FREQ_CAP_REG_1						CCR2
#define FREQ_CAP_REG_2						CCR3

#define FREQ_COUNT_2_TIM					TIM1
#define FREQ_COUNT_2_GPIO_AF 				GPIO_AF_TIM1
#define RCC_FREQ_COUNT_2_TIM 				RCC_APB2Periph_TIM1
#define	RCC_FREQ_COUNT_2_GPIO_PORT			RCC_AHB1Periph_GPIOA
#define FREQ_COUNT_2_GPIO_PORT				GPIOA
#define FREQ_COUNT_2_GPIO_PINS				GPIO_Pin_12
#define FREQ_COUNT_2_GPIO_PINSOURCE			GPIO_PinSource12
#define FREQ_COUNT_2_TIM_PERIOD				(65535)

#define FREQ_COUNT_1_TIM					TIM8
#define FREQ_COUNT_1_GPIO_AF 				GPIO_AF_TIM8
#define RCC_FREQ_COUNT_1_TIM 				RCC_APB2Periph_TIM8
#define	RCC_FREQ_COUNT_1_GPIO_PORT			RCC_AHB1Periph_GPIOA
#define FREQ_COUNT_1_GPIO_PORT				GPIOA
#define FREQ_COUNT_1_GPIO_PINS				GPIO_Pin_0
#define FREQ_COUNT_1_GPIO_PINSOURCE			GPIO_PinSource0
#define FREQ_COUNT_1_TIM_PERIOD				(65535)

#define FREQ_MEASURE_TIME					250

void FrequencyMeasureInit(void);

#endif
